# Generated by Django 5.2 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=50),
            preserve_default=False,
        ),
    ]
