# Generated by Django 5.2 on 2025-04-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
        migrations.AlterModelTable(
            name='filetype',
            table='file_type',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
