# Generated by Django 5.2 on 2025-05-13 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, to='social.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('none', 'none')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_id',
            field=models.CharField(max_length=36, unique=True, validators=[django.core.validators.MinLengthValidator(36)]),
        ),
    ]
