# Generated by Django 5.2 on 2025-04-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_file_table_alter_filetype_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
