# Generated by Django 5.2 on 2025-04-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0003_remove_file_type_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'file_type',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.filetype')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.file')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
