# Generated by Django 5.2 on 2025-05-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_user_followers_alter_post_file_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='following',
        ),
    ]
