# Generated by Django 5.2 on 2025-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image/jpeg', 'image/jpeg'), ('image/png', 'image/png'), ('image/webp', 'image/webp'), ('image/gif', 'image/gif'), ('video/mp4', 'video/mp4')], max_length=100),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
